spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      topics: vwap-event-v1
      concurrency: 15
      group-id: vwap-event-v1.vwap-app
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true